name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Installer les dépendances backend
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      # 4. Construire l’image Docker backend
      - name: Build Docker image backend
        run: docker build -t pfehatim-backend:latest ./backend

      # 5. Installer les dépendances frontend
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      # 6. Construire l’image Docker frontend
      - name: Build Docker image frontend
        run: docker build -t pfehatim-frontend:latest ./frontend

      # 7. Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Pousser les images sur Docker Hub
      - name: Push Docker images
        run: |
          docker tag pfehatim-backend:latest ${{ secrets.DOCKER_USERNAME }}/pfehatim-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/pfehatim-backend:latest
          docker tag pfehatim-frontend:latest ${{ secrets.DOCKER_USERNAME }}/pfehatim-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/pfehatim-frontend:latest

      # 9. Déployer sur le serveur via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Backend
            docker rm -f pfehatim-backend || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/pfehatim-backend:latest
            docker run -d --name pfehatim-backend -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/pfehatim-backend:latest

            # Frontend
            docker rm -f pfehatim-frontend || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/pfehatim-frontend:latest
            docker run -d --name pfehatim-frontend -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/pfehatim-frontend:latest
