name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # ou 'master' si ton projet est sur master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer ton code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Se connecter à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Backend: installer dépendances et build/push Docker
      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: nassimidr/pfehatim-backend:latest

      # 4️⃣ Frontend: installer dépendances et build/push Docker
      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: nassimidr/pfehatim-frontend:latest

      # 5️⃣ Déploiement SSH (commenté pour l’instant)
      # - name: Deploy to Server
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       cd /chemin/vers/ton/projet
      #       docker-compose pull
      #       docker-compose up -d
