name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # ou 'master' selon ton projet

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Tester le backend
      - name: Run Backend Tests
        working-directory: ./backend
        run: |
          npm install
          npm test

      # 3️⃣ Tester le frontend
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: |
          npm install
          npm test

      # 4️⃣ Se connecter à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5️⃣ Construire et pousser l'image backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: nassimidr/pfehatim-backend:latest

      # 6️⃣ Construire et pousser l'image frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: nassimidr/pfehatim-frontend:latest

      # 7️⃣ Déploiement sur serveur via SSH (optionnel)
      # Ajouter les secrets : SSH_HOST, SSH_USER, SSH_KEY dans GitHub
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /chemin/vers/ton/projet
            docker-compose pull
            docker-compose up -d
